language: go

go:
  - master

install:
  - go get github.com/gohugoio/hugo

script:
  - hugo

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master