baseURL = "https://dominiccobo-fyp.github.io/docs/"
languageCode = "en-GB"
title = "GCS Docs"
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "blue"